# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('current_balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
