# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
