# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSparepartRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='sparepart',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='sparepart_count',
        ),
        migrations.AddField(
            model_name='devicesparepartrelation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spareparts', to='devices.MaintenanceDevice'),
        ),
        migrations.AddField(
            model_name='devicesparepartrelation',
            name='sparepart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.Sparepart'),
        ),
    ]
