# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_maintenancedevice_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesparepartrelation',
            name='diagram_code',
            field=models.CharField(default='', max_length=300),
        ),
    ]
