# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=300)),
                ('inner_representative', models.CharField(default='', max_length=300)),
                ('outer_representative', models.CharField(default='', max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceptionReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=300)),
                ('inner_representative', models.CharField(default='', max_length=300)),
                ('outer_representative', models.CharField(default='', max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
