# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-17 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receptionreceipt',
            name='synced',
            field=models.BooleanField(default=True),
        ),
    ]
